<?php
/**
 * Created by PhpStorm.
 * User: puneet
 * Date: 2/28/14
 * Time: 3:37 PM
 */

/**
 * Implementation of hook_preprocess_views_view
 * @param $vars
 */
function chf_custom_preprocess_views_view(&$vars) {
  // Check for user profile page
  /*if ($vars['view']->name == 'user_profile_page') {

    // check the path for loading the user details
    if(arg(0) =='user' && is_numeric(arg(1))) {
      $user_details = user_load(arg(1));

      //Change the title
      $vars['view']->build_info['title'] = $user_details->field_first_name[LANGUAGE_NONE][0]['value'] . ' ' .
            $user_details->field_last_name[LANGUAGE_NONE][0]['value'];
    }
  }*/
}

function chf_custom_views_post_execute(&$view) {
    if ($view->pager['use_pager'] == '1') {
        $current_page = $view->pager['current_page'];
        $items_per_page = $view->pager['items_per_page'];
        $lastItemViewed = ($current_page * $items_per_page) + $items_per_page;
        global $base_url;
        if ($current_page != 0) {
            // add rel="prev" link
            $url = $_SERVER['REQUEST_URI'];
            $url = chf_custom_setPageInURL($url, $current_page - 1, $current_page);
            $url = $base_url . $url;
            drupal_set_html_head('<link rel="prev" href="' . $url . '" />');
        }
        if ($view->total_rows > $lastItemViewed) {
            // Add rel="next" link
            $url = $_SERVER['REQUEST_URI'];
            $url = chf_custom_setPageInURL($url, $current_page + 1, $current_page);
            $url = $base_url . $url;
            drupal_set_html_head('<link rel="next" href="' . $url . '" />');
        }
    }
}

function chf_custom_setPageInURL($url, $page, $curPage) {
    if ($curPage == 0) {
        if (strpos($url, '?') !== FALSE) {
            $url .= '&page=' . $page;
        } else {
            $url .= '?page=' . $page;
        }
    } else {
        if ($page != 0) {
            $url = str_replace('page=' . $curPage, 'page=' . $page, $url);
        } else {
            $url = str_replace('page=' . $curPage, '', $url);
            if (substr($url, -1) === '?') {
                $url = str_replace('?', '', $url);
            }
        }
    }
    return $url;
}
